resources:
  repositories:
  - repository: templates
    type: git
    name: stages-templates/stages-templates

variables:
  ProjectName: Twia.AzureFunctions.Extensions.OpenApi
  CompanyName: TWIA
  Solution: $(ProjectName).sln
  BuildPlatform: Any CPU
  BuildConfiguration: Release
  SonarProjectKey: TwiaFnOpenApi
  ScriptsArtifactName: Scripts
  FunctionArtifactName: Function
  IntegrationTestsArtifactName: Tests
  GitVersionJsonFile: GitVersionVariables.json

trigger:
  batch: true
  branches:
    include:
    - '*'

stages:
  template: ReleaseScripts/build-stage.yml
