resources:
  repositories:
  - repository: templates
    type: git
    name: Twia.Templates/Twia.Templates

variables:
  ProjectName: Twia.AzureFunctions.Extensions.OpenApi
  CompanyName: TWIA
  Solution: $(ProjectName).sln
  BuildPlatform: Any CPU
  BuildConfiguration: Release
  SonarConnection: SonarCloud TWIA
  SonarOrganization: twia
  SonarProjectKey: TwiaFnOpenApi
  ScriptsArtifactName: Scripts
  PackagesArtifactName: Packages
  GitVersionJsonFile: GitVersionVariables.json

trigger:
  batch: true
  branches:
    include:
    - '*'

stages:
- template: ReleaseScripts/build-stage.yml
