stages:

- stage: release
  displayName: publish to release feed
  dependsOn: build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:

  - job: publish_release
    displayName: publish to release feed
    pool:
      vmImage: windows-latest
    steps:

    - task: NuGetCommand@2
      displayName: Push to NuGet
      inputs:
        command: push
        packagesToPush: $(Pipeline.Workspace)/$(PackagesArtifactName)/*.nupkg
        nuGetFeedType: external
        publishFeedCredentials: NuGet.org Twia.AzureFunctions.Extensions.OpenApi
