stages:

- stage: tag
  displayName: Tag Sources after Release
  dependsOn: release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:

  - job: tag_build
    displayName: Tag Sources
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: GitHubTag@1
      inputs:
        githubEndpoint: $(GitHubEndpoint)
        repositoryName: $(Build.Repository.Name)
        tag: $(Build.BuildNumber)